export class Constants {
    static readonly CAN_VIEW_DASHBOARD = "CAN_VIEW_DASHBOARD";
    static readonly CAN_VIEW_MANUAL_SCORE = "CAN_VIEW_MANUAL_SCORE";
    static readonly CAN_VIEW_ATTRIBUTES_VALUES = "CAN_VIEW_ATTRIBUTES_VALUES";
    static readonly CAN_VIEW_SCORES_LIST = "CAN_VIEW_SCORES_LIST";
    static readonly CAN_VIEW_QUESTIONS_MANAGEMENT = "CAN_VIEW_QUESTIONS_MANAGEMENT";
    static readonly CAN_VIEW_CATEGORIES_MANAGEMENT = "CAN_VIEW_CATEGORIES_MANAGEMENT";
    static readonly CAN_ADD_MANUAL_SCORE = "CAN_ADD_MANUAL_SCORE";
    static readonly CAN_VALIDATE_SCORE = "CAN_VALIDATE_SCORE";
}